import type { Tenant } from '@/types';

export const mockTenants: Tenant[] = [
  {
    id: 'tenant-001',
    name: 'Delightrics Demo Corp',
    industry: 'Retail',
    kpiSummaries: [
      {
        category: 'CHS',
        title: 'Customer Happiness Score',
        color: '#22d3ee', // cyan-400
        kpis: [
          {
            id: 'chs-overall',
            category: 'CHS',
            label: 'Overall CHS',
            description: 'Weighted average happiness across all touchpoints',
            value: 84,
            target: 90,
            unit: '%',
            trend: 'up',
            trendValue: 3.2,
            period: 'Q1 2026',
          },
          {
            id: 'chs-post-purchase',
            category: 'CHS',
            label: 'Post-Purchase CHS',
            description: 'Happiness score after order delivery',
            value: 88,
            target: 92,
            unit: '%',
            trend: 'up',
            trendValue: 1.8,
            period: 'Q1 2026',
          },
          {
            id: 'chs-support',
            category: 'CHS',
            label: 'Support CHS',
            description: 'Happiness score after support interactions',
            value: 76,
            target: 85,
            unit: '%',
            trend: 'down',
            trendValue: -2.1,
            period: 'Q1 2026',
          },
        ],
      },
      {
        category: 'CES',
        title: 'Customer Effort Score',
        color: '#a78bfa', // violet-400
        kpis: [
          {
            id: 'ces-overall',
            category: 'CES',
            label: 'Overall CES',
            description: 'How easy it is to do business with us (lower = better)',
            value: 2.3,
            target: 2.0,
            unit: '/7',
            trend: 'down',
            trendValue: -0.4,
            period: 'Q1 2026',
          },
          {
            id: 'ces-checkout',
            category: 'CES',
            label: 'Checkout CES',
            description: 'Effort score at the checkout flow',
            value: 1.9,
            target: 1.5,
            unit: '/7',
            trend: 'down',
            trendValue: -0.6,
            period: 'Q1 2026',
          },
          {
            id: 'ces-returns',
            category: 'CES',
            label: 'Returns CES',
            description: 'Effort score when initiating a return',
            value: 3.1,
            target: 2.5,
            unit: '/7',
            trend: 'stable',
            trendValue: 0.0,
            period: 'Q1 2026',
          },
        ],
      },
      {
        category: 'NPS',
        title: 'Net Promoter Score',
        color: '#34d399', // emerald-400
        kpis: [
          {
            id: 'nps-overall',
            category: 'NPS',
            label: 'Overall NPS',
            description: 'Likelihood to recommend (−100 to +100)',
            value: 52,
            target: 60,
            unit: '',
            trend: 'up',
            trendValue: 5.0,
            period: 'Q1 2026',
          },
          {
            id: 'nps-promoters',
            category: 'NPS',
            label: 'Promoters',
            description: 'Percentage of customers scoring 9–10',
            value: 64,
            target: 70,
            unit: '%',
            trend: 'up',
            trendValue: 4.2,
            period: 'Q1 2026',
          },
          {
            id: 'nps-detractors',
            category: 'NPS',
            label: 'Detractors',
            description: 'Percentage of customers scoring 0–6',
            value: 12,
            target: 10,
            unit: '%',
            trend: 'down',
            trendValue: -0.8,
            period: 'Q1 2026',
          },
        ],
      },
      {
        category: 'EHS',
        title: 'Employee Happiness Score',
        color: '#fb923c', // orange-400
        kpis: [
          {
            id: 'ehs-overall',
            category: 'EHS',
            label: 'Overall EHS',
            description: 'Employee satisfaction averaged across departments',
            value: 78,
            target: 85,
            unit: '%',
            trend: 'up',
            trendValue: 2.5,
            period: 'Q1 2026',
          },
          {
            id: 'ehs-engagement',
            category: 'EHS',
            label: 'Engagement Score',
            description: 'Active engagement in work and culture',
            value: 72,
            target: 80,
            unit: '%',
            trend: 'stable',
            trendValue: 0.3,
            period: 'Q1 2026',
          },
          {
            id: 'ehs-retention',
            category: 'EHS',
            label: 'Retention Index',
            description: 'Likelihood employees remain for 12+ months',
            value: 88,
            target: 90,
            unit: '%',
            trend: 'up',
            trendValue: 1.2,
            period: 'Q1 2026',
          },
        ],
      },
      {
        category: 'OX',
        title: 'Operational Excellence',
        color: '#f472b6', // pink-400
        kpis: [
          {
            id: 'ox-fulfillment',
            category: 'OX',
            label: 'Fulfillment Rate',
            description: 'Orders fulfilled on time and in full',
            value: 96.4,
            target: 98,
            unit: '%',
            trend: 'up',
            trendValue: 0.9,
            period: 'Q1 2026',
          },
          {
            id: 'ox-resolution-time',
            category: 'OX',
            label: 'Avg Resolution Time',
            description: 'Mean time to resolve a customer issue',
            value: 4.2,
            target: 3.0,
            unit: 'hrs',
            trend: 'down',
            trendValue: -0.5,
            period: 'Q1 2026',
          },
          {
            id: 'ox-first-contact',
            category: 'OX',
            label: 'First Contact Resolution',
            description: 'Issues resolved on the first contact',
            value: 81,
            target: 88,
            unit: '%',
            trend: 'up',
            trendValue: 2.0,
            period: 'Q1 2026',
          },
        ],
      },
    ],
  },
];

export const activeTenant = mockTenants[0];
